//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 02:12:21 odp. CET 
//

package cz.sirsi.ancestry.core.load.rodx;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fontType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;fontType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;Charset&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;Color&quot; type=&quot;{}color&quot;/&gt;
 *         &lt;element name=&quot;Height&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}integer&quot;/&gt;
 *         &lt;element name=&quot;Size&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}integer&quot;/&gt;
 *         &lt;element name=&quot;Italic&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot;/&gt;
 *         &lt;element name=&quot;Bold&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot;/&gt;
 *         &lt;element name=&quot;Underline&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot;/&gt;
 *         &lt;element name=&quot;StrikeOut&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fontType", propOrder = { "name", "charset", "color", "height", "size", "italic", "bold", "underline",
		"strikeOut" })
@SuppressWarnings("all")
public class FontType {

	@XmlElement(name = "Name", required = true)
	protected String name;
	@XmlElement(name = "Charset", required = true)
	protected String charset;
	@XmlElement(name = "Color")
	protected long color;
	@XmlElement(name = "Height", required = true)
	protected BigInteger height;
	@XmlElement(name = "Size", required = true)
	protected BigInteger size;
	@XmlElement(name = "Italic")
	protected boolean italic;
	@XmlElement(name = "Bold")
	protected boolean bold;
	@XmlElement(name = "Underline")
	protected boolean underline;
	@XmlElement(name = "StrikeOut")
	protected boolean strikeOut;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the charset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCharset() {
		return charset;
	}

	/**
	 * Sets the value of the charset property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCharset(String value) {
		this.charset = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 */
	public long getColor() {
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 */
	public void setColor(long value) {
		this.color = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getHeight() {
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setHeight(BigInteger value) {
		this.height = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSize() {
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setSize(BigInteger value) {
		this.size = value;
	}

	/**
	 * Gets the value of the italic property.
	 * 
	 */
	public boolean isItalic() {
		return italic;
	}

	/**
	 * Sets the value of the italic property.
	 * 
	 */
	public void setItalic(boolean value) {
		this.italic = value;
	}

	/**
	 * Gets the value of the bold property.
	 * 
	 */
	public boolean isBold() {
		return bold;
	}

	/**
	 * Sets the value of the bold property.
	 * 
	 */
	public void setBold(boolean value) {
		this.bold = value;
	}

	/**
	 * Gets the value of the underline property.
	 * 
	 */
	public boolean isUnderline() {
		return underline;
	}

	/**
	 * Sets the value of the underline property.
	 * 
	 */
	public void setUnderline(boolean value) {
		this.underline = value;
	}

	/**
	 * Gets the value of the strikeOut property.
	 * 
	 */
	public boolean isStrikeOut() {
		return strikeOut;
	}

	/**
	 * Sets the value of the strikeOut property.
	 * 
	 */
	public void setStrikeOut(boolean value) {
		this.strikeOut = value;
	}

}
