//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 02:12:21 odp. CET 
//

package cz.sirsi.ancestry.core.load.rodx;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>
 * Java class for genderType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;genderType&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;M&quot;/&gt;
 *     &lt;enumeration value=&quot;F&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum
@SuppressWarnings("all")
public enum GenderType {

	M, F;

	public String value() {
		return name();
	}

	public static GenderType fromValue(String v) {
		return valueOf(v);
	}

}
