//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 02:12:21 odp. CET 
//

package cz.sirsi.ancestry.core.load.rodx;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * cz.sirsi.ancestry.core.load.rodx package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
@SuppressWarnings("all")
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * cz.sirsi.ancestry.core.load.rodx
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities createAncestryTreesTreeEntities() {
		return new Ancestry.Trees.Tree.Entities();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityFlowline }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityFlowline createAncestryTreesTreeEntitiesEntityFlowline() {
		return new Ancestry.Trees.Tree.Entities.EntityFlowline();
	}

	/**
	 * Create an instance of {@link Ancestry.Photos.Photo }
	 * 
	 */
	public Ancestry.Photos.Photo createAncestryPhotosPhoto() {
		return new Ancestry.Photos.Photo();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree }
	 * 
	 */
	public Ancestry.Trees.Tree createAncestryTreesTree() {
		return new Ancestry.Trees.Tree();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityLine }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityLine createAncestryTreesTreeEntitiesEntityLine() {
		return new Ancestry.Trees.Tree.Entities.EntityLine();
	}

	/**
	 * Create an instance of {@link Ancestry.General.UserDefined }
	 * 
	 */
	public Ancestry.General.UserDefined createAncestryGeneralUserDefined() {
		return new Ancestry.General.UserDefined();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityWeddingLine }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityWeddingLine createAncestryTreesTreeEntitiesEntityWeddingLine() {
		return new Ancestry.Trees.Tree.Entities.EntityWeddingLine();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityBrokenLine }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityBrokenLine createAncestryTreesTreeEntitiesEntityBrokenLine() {
		return new Ancestry.Trees.Tree.Entities.EntityBrokenLine();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Photos }
	 * 
	 */
	public Ancestry.People.Person.Photos createAncestryPeoplePersonPhotos() {
		return new Ancestry.People.Person.Photos();
	}

	/**
	 * Create an instance of {@link Ancestry.General }
	 * 
	 */
	public Ancestry.General createAncestryGeneral() {
		return new Ancestry.General();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person }
	 * 
	 */
	public Ancestry.People.Person createAncestryPeoplePerson() {
		return new Ancestry.People.Person();
	}

	/**
	 * Create an instance of {@link Ancestry.Version }
	 * 
	 */
	public Ancestry.Version createAncestryVersion() {
		return new Ancestry.Version();
	}

	/**
	 * Create an instance of {@link Ancestry }
	 * 
	 */
	public Ancestry createAncestry() {
		return new Ancestry();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Documents }
	 * 
	 */
	public Ancestry.People.Person.Documents createAncestryPeoplePersonDocuments() {
		return new Ancestry.People.Person.Documents();
	}

	/**
	 * Create an instance of {@link Ancestry.Partnerships.Partnership }
	 * 
	 */
	public Ancestry.Partnerships.Partnership createAncestryPartnershipsPartnership() {
		return new Ancestry.Partnerships.Partnership();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Files }
	 * 
	 */
	public Ancestry.People.Person.Files createAncestryPeoplePersonFiles() {
		return new Ancestry.People.Person.Files();
	}

	/**
	 * Create an instance of {@link FontType }
	 * 
	 */
	public FontType createFontType() {
		return new FontType();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Residence }
	 * 
	 */
	public Ancestry.People.Person.Residence createAncestryPeoplePersonResidence() {
		return new Ancestry.People.Person.Residence();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Death }
	 * 
	 */
	public Ancestry.People.Person.Death createAncestryPeoplePersonDeath() {
		return new Ancestry.People.Person.Death();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityPerson }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityPerson createAncestryTreesTreeEntitiesEntityPerson() {
		return new Ancestry.Trees.Tree.Entities.EntityPerson();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Education }
	 * 
	 */
	public Ancestry.People.Person.Education createAncestryPeoplePersonEducation() {
		return new Ancestry.People.Person.Education();
	}

	/**
	 * Create an instance of {@link Ancestry.Groups.Group }
	 * 
	 */
	public Ancestry.Groups.Group createAncestryGroupsGroup() {
		return new Ancestry.Groups.Group();
	}

	/**
	 * Create an instance of {@link Ancestry.People }
	 * 
	 */
	public Ancestry.People createAncestryPeople() {
		return new Ancestry.People();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Birth }
	 * 
	 */
	public Ancestry.People.Person.Birth createAncestryPeoplePersonBirth() {
		return new Ancestry.People.Person.Birth();
	}

	/**
	 * Create an instance of {@link Ancestry.Version.CanBeOpenedFrom }
	 * 
	 */
	public Ancestry.Version.CanBeOpenedFrom createAncestryVersionCanBeOpenedFrom() {
		return new Ancestry.Version.CanBeOpenedFrom();
	}

	/**
	 * Create an instance of {@link Ancestry.Documents }
	 * 
	 */
	public Ancestry.Documents createAncestryDocuments() {
		return new Ancestry.Documents();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityComment }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityComment createAncestryTreesTreeEntitiesEntityComment() {
		return new Ancestry.Trees.Tree.Entities.EntityComment();
	}

	/**
	 * Create an instance of {@link Ancestry.Groups.Group.Members }
	 * 
	 */
	public Ancestry.Groups.Group.Members createAncestryGroupsGroupMembers() {
		return new Ancestry.Groups.Group.Members();
	}

	/**
	 * Create an instance of {@link Ancestry.Files.File }
	 * 
	 */
	public Ancestry.Files.File createAncestryFilesFile() {
		return new Ancestry.Files.File();
	}

	/**
	 * Create an instance of {@link Ancestry.Documents.Document }
	 * 
	 */
	public Ancestry.Documents.Document createAncestryDocumentsDocument() {
		return new Ancestry.Documents.Document();
	}

	/**
	 * Create an instance of {@link Ancestry.People.Person.Occupation }
	 * 
	 */
	public Ancestry.People.Person.Occupation createAncestryPeoplePersonOccupation() {
		return new Ancestry.People.Person.Occupation();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityDoubleBrokenLine }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityDoubleBrokenLine createAncestryTreesTreeEntitiesEntityDoubleBrokenLine() {
		return new Ancestry.Trees.Tree.Entities.EntityDoubleBrokenLine();
	}

	/**
	 * Create an instance of {@link Ancestry.Files }
	 * 
	 */
	public Ancestry.Files createAncestryFiles() {
		return new Ancestry.Files();
	}

	/**
	 * Create an instance of {@link Ancestry.Partnerships }
	 * 
	 */
	public Ancestry.Partnerships createAncestryPartnerships() {
		return new Ancestry.Partnerships();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees.Tree.Entities.EntityWeddingLine.EntityWedding }
	 * 
	 */
	public Ancestry.Trees.Tree.Entities.EntityWeddingLine.EntityWedding createAncestryTreesTreeEntitiesEntityWeddingLineEntityWedding() {
		return new Ancestry.Trees.Tree.Entities.EntityWeddingLine.EntityWedding();
	}

	/**
	 * Create an instance of {@link Ancestry.Photos }
	 * 
	 */
	public Ancestry.Photos createAncestryPhotos() {
		return new Ancestry.Photos();
	}

	/**
	 * Create an instance of {@link Ancestry.Groups }
	 * 
	 */
	public Ancestry.Groups createAncestryGroups() {
		return new Ancestry.Groups();
	}

	/**
	 * Create an instance of {@link Ancestry.Trees }
	 * 
	 */
	public Ancestry.Trees createAncestryTrees() {
		return new Ancestry.Trees();
	}

	/**
	 * Create an instance of {@link TextLines }
	 * 
	 */
	public TextLines createTextLines() {
		return new TextLines();
	}

}
